### ISSUE TITLE
[Feature Request]: Finish Overview tab

### ISSUE THREAD

**Issue by GregJohnStewart** [Epic-Breakfast-Productions/OpenQuarterMaster#45]
### Software

Base Station

### Describe what you'd like to see

```[tasklist]
### Tasks
- [x] explore- add images
- [x] explore- storage block details
- [x] explore- item details
- [x] explore- Storage Block View Link
- [x] explore- Item view link
- [x] low stock- finish actions
```

### Describe alternatives you've considered

None

### Additional context

None
